# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\PyCharm - JetBrains IDE\Wallpaper Widget\ADVANCEMENT.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()

        self.setupUi()

    def clicked(self):
        print("hi")
        app = QtWidgets.QApplication(sys.argv)
        a = Ui_MainWindow()
        sys.exit(app.exec_())

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(769, 850)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.desktopPreview = QtWidgets.QLabel(self.centralwidget)
        self.desktopPreview.setText("")
        self.desktopPreview.setPixmap(QtGui.QPixmap("D:/Downloads/Minecraft Plugins/Digtorus/Logo copy.JPG"))
        self.desktopPreview.setScaledContents(True)
        self.desktopPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.desktopPreview.setObjectName("desktopPreview")
        self.gridLayout.addWidget(self.desktopPreview, 4, 0, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 1, 0, 1, 1)
        self.wallpaperSetterFrame = QtWidgets.QFrame(self.centralwidget)
        self.wallpaperSetterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wallpaperSetterFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.wallpaperSetterFrame.setObjectName("wallpaperSetterFrame")
        self.gridLayoutChooseWallpaper = QtWidgets.QGridLayout(self.wallpaperSetterFrame)
        self.gridLayoutChooseWallpaper.setObjectName("gridLayoutChooseWallpaper")
        self.setAsWallpaper = QtWidgets.QPushButton(self.wallpaperSetterFrame)
        self.setAsWallpaper.setCheckable(False)
        self.setAsWallpaper.setAutoDefault(False)
        self.setAsWallpaper.setDefault(False)
        self.setAsWallpaper.setFlat(False)
        self.setAsWallpaper.setObjectName("setAsWallpaper")
        self.gridLayoutChooseWallpaper.addWidget(self.setAsWallpaper, 0, 0, 1, 1)
        self.selectedImageDimensions = QtWidgets.QLabel(self.wallpaperSetterFrame)
        self.selectedImageDimensions.setObjectName("selectedImageDimensions")
        self.gridLayoutChooseWallpaper.addWidget(self.selectedImageDimensions, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.wallpaperSetterFrame)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clicked())
        self.gridLayoutChooseWallpaper.addWidget(self.pushButton, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.wallpaperSetterFrame, 1, 1, 1, 1)
        self.monitorChangerFrame = QtWidgets.QFrame(self.centralwidget)
        self.monitorChangerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.monitorChangerFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.monitorChangerFrame.setObjectName("monitorChangerFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.monitorChangerFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.monitorChangerFrame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.checkBox = QtWidgets.QCheckBox(self.monitorChangerFrame)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.gridLayout.addWidget(self.monitorChangerFrame, 4, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.currentInfoFrame = QtWidgets.QFrame(self.centralwidget)
        self.currentInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.currentInfoFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.currentInfoFrame.setObjectName("currentInfoFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.currentInfoFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentWallpaperDimensions = QtWidgets.QLabel(self.currentInfoFrame)
        self.currentWallpaperDimensions.setObjectName("currentWallpaperDimensions")
        self.horizontalLayout.addWidget(self.currentWallpaperDimensions)
        self.monitorResolution = QtWidgets.QLabel(self.currentInfoFrame)
        self.monitorResolution.setObjectName("monitorResolution")
        self.horizontalLayout.addWidget(self.monitorResolution)
        self.gridLayout.addWidget(self.currentInfoFrame, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        self.treeView.clicked['QModelIndex'].connect(self.close)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.setAsWallpaper.setText(_translate("MainWindow", "Set as Wallpaper"))
        self.selectedImageDimensions.setText(_translate("MainWindow", "Selected Image Dimensions: "))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.checkBox.setToolTip(_translate("MainWindow", "When ticked, the wallpaper preview will\n"
"update to the wallpaper of the monitor\n"
"that the window is currently on."))
        self.checkBox.setText(_translate("MainWindow", "Wallpaper Auto-update"))
        self.currentWallpaperDimensions.setText(_translate("MainWindow", "Current Wallpaper Dimensions: 1920x1080"))
        self.monitorResolution.setText(_translate("MainWindow", "Monitor Resolution: 1920x1080"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    sys.exit(app.exec_())
